version: "2.4"
services:
  plugin_crawler_html:
    image: docker.io/isoxya/isoxya-plugin-crawler-html:stable
    init: true
    networks:
      processor:
        aliases:
          - isoxya-plugin-crawler-html.localhost
    restart: on-failure
networks:
  processor: {}
